#include "board.h"

#include "Task/z_main.h"
#include "Task/can_callbacks.h"
#include "freertos_vars.h"

#include "main.h"
#include "adc.h"
#include "can.h"
#include "dma.h"
#include "i2c.h"
#include "iwdg.h"
#include "spi.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

extern "C" void SystemClock_Config(void);

void system_init() {
    HAL_Init();
    SystemClock_Config();
}

bool board_init() {
    // Initialize all configured peripherals
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_ADC1_Init();
    MX_ADC2_Init();
    MX_ADC3_Init();
    MX_CAN1_Init();
    MX_CAN2_Init();
    MX_I2C1_Init();
    MX_SPI1_Init();
    MX_SPI2_Init();
    MX_UART5_Init();
    MX_USART1_UART_Init();
    MX_USART2_UART_Init();
    MX_USART3_UART_Init();
    MX_USART6_UART_Init();
    MX_TIM2_Init();
    MX_TIM6_Init();
    MX_UART4_Init();
    MX_IWDG_Init();
    MX_TIM1_Init();
    MX_TIM13_Init();
    MX_TIM7_Init();

    HAL_IWDG_Refresh(&hiwdg);

    // Initialize ZCAN for CAN1 and CAN2
    if (!can1_bus.start(&hcan1)) {
        return false;
    }
    if (!can2_bus.start(&hcan2)) {
        return false;
    }
    
    // Subscribe to optical flow sensor (CAN1, ID 0x300-0x301)
    MsgIdFilterSpecs optflow_filter;
    optflow_filter.id = (uint16_t)0x300;
    optflow_filter.mask = 0x7FE;  // Match IDs 0x300-0x301
    optflow_filter.fifo = CAN_RX_FIFO0;
    can1_bus.subscribe(optflow_filter, on_optflow_rx, nullptr, nullptr);
    
    // Subscribe to dribbler ZFOC heartbeat (CAN1, node_id=5, cmd=0x001 -> ID 0x0A1)
    MsgIdFilterSpecs dribbler_filter;
    dribbler_filter.id = (uint16_t)((5 << 5) | 0x001);
    dribbler_filter.mask = 0x7FF;  // Match exact ID
    dribbler_filter.fifo = CAN_RX_FIFO0;
    can1_bus.subscribe(dribbler_filter, on_dribbler_heartbeat_rx, &robot.dribbler, nullptr);

    // Subscribe to motor feedback (CAN2, exact wheel feedback IDs only).
    for (uint8_t i = 0; i < 4; ++i) {
        MsgIdFilterSpecs motor_filter;
        motor_filter.id = static_cast<uint16_t>(robot.wheel_motors[i]->feedback_can_id());
        motor_filter.mask = 0x7FF;
        motor_filter.fifo = CAN_RX_FIFO1;
        can2_bus.subscribe(motor_filter, on_motor_fb_rx, robot.wheel_motors[i], nullptr);
    }

    imu.init();

    HAL_TIM_Base_Start_IT(&htim2);

    if (imu.model() == IMU::Model::kIcm42688) {
        HAL_TIM_Base_Start_IT(&htim7);
    }

    // Start TIM13 for optical flow sensor timing
    HAL_TIM_Base_Start(&htim13);

    return true;
}


extern volatile uint32_t spi_error_irq_count;
extern volatile uint32_t spi_last_error;
extern volatile uint32_t spi_last_sr;
extern volatile uint8_t spi_recover_requested;
extern "C" {

// FIXME: This function is auto-generated by STM32CubeMX in main.c.
// Comment it out there to avoid redefinition errors.
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM14)
    {
        HAL_IncTick();
    }

    if (htim->Instance == TIM2) {
        osSemaphoreRelease(sem_ctrl_triggerHandle);
    }

    if (htim->Instance == TIM7) {
        if (imu.model() == IMU::Model::kIcm42688) {
            osSemaphoreRelease(sem_imu_readyHandle);
        }
    }

    if (htim->Instance == TIM6) {
        robot.on_kick_timeout_irq();
    }
}

// CAN RX FIFO0 callback for CAN1 (optical flow)
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan) {
    if (hcan->Instance == CAN1) {
        can1_bus.process_rx_fifo(CAN_RX_FIFO0);
    }
}

// CAN RX FIFO1 callback for CAN2 (motors)
void HAL_CAN_RxFifo1MsgPendingCallback(CAN_HandleTypeDef *hcan) {
    if (hcan->Instance == CAN2) {
        can2_bus.process_rx_fifo(CAN_RX_FIFO1);
    }
}

void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi == imu.spi_handle()) {
        // ICM42688 uses TIM7-triggered polling, not SPI IRQ wakeups.
    }
    if (hspi->Instance == SPI1) {
        // Trigger SPI exchange task, similar to ctrl task trigger flow
        if (sem_spi_triggerHandle != nullptr) {
            osSemaphoreRelease(sem_spi_triggerHandle);
        }
    }
}

void HAL_SPI_ErrorCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi->Instance != SPI1) {
        return;
    }

    spi_error_irq_count++;
    spi_last_error = HAL_SPI_GetError(hspi);
    spi_last_sr = hspi->Instance->SR;
    spi_recover_requested = 1;
    if (sem_spi_triggerHandle != nullptr) {
        osSemaphoreRelease(sem_spi_triggerHandle);
    }
}

extern DMA_HandleTypeDef *hdma_uart4_rx;
// Due to high priority of DMA interrupts, FreeRTOS functions are not allowed here.
void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart, uint16_t Size)
{
    (void)Size;

    if (huart->Instance == USART1) {
        
    }

    if (huart->Instance == UART4) {
        // UART4 not used (JY931 IMU removed)
    }
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) {
        
    }

    if (huart->Instance == UART4) {
    }
}

} // extern "C"

